[2024-11-14T20:38:48.486+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T20:38:48.511+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_data_into_Postgres.bash_task_tar manual__2024-11-14T20:38:41.702553+00:00 [queued]>
[2024-11-14T20:38:48.527+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_data_into_Postgres.bash_task_tar manual__2024-11-14T20:38:41.702553+00:00 [queued]>
[2024-11-14T20:38:48.528+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-14T20:38:48.551+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): bash_task_tar> on 2024-11-14 20:38:41.702553+00:00
[2024-11-14T20:38:48.559+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T20:38:48.561+0000] {standard_task_runner.py:72} INFO - Started process 248 to run task
[2024-11-14T20:38:48.561+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Extract_data_into_Postgres', 'bash_task_tar', 'manual__2024-11-14T20:38:41.702553+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_download.py', '--cfg-path', '/tmp/tmp3kh6y0ev']
[2024-11-14T20:38:48.565+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask bash_task_tar
[2024-11-14T20:38:48.635+0000] {task_command.py:467} INFO - Running <TaskInstance: Extract_data_into_Postgres.bash_task_tar manual__2024-11-14T20:38:41.702553+00:00 [running]> on host d3fd5b1c3aa1
[2024-11-14T20:38:48.753+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ProjectIE' AIRFLOW_CTX_DAG_ID='Extract_data_into_Postgres' AIRFLOW_CTX_TASK_ID='bash_task_tar' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T20:38:41.702553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T20:38:41.702553+00:00'
[2024-11-14T20:38:48.755+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T20:38:48.762+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T20:38:48.766+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'tar -xf archive.zip']
[2024-11-14T20:38:48.778+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T20:38:48.789+0000] {subprocess.py:93} INFO - tar: This does not look like a tar archive
[2024-11-14T20:38:48.790+0000] {subprocess.py:93} INFO - tar: Skipping to next header
[2024-11-14T20:38:48.792+0000] {subprocess.py:93} INFO - tar: Exiting with failure status due to previous errors
[2024-11-14T20:38:48.793+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-14T20:38:48.805+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-14T20:38:48.813+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_data_into_Postgres, task_id=bash_task_tar, run_id=manual__2024-11-14T20:38:41.702553+00:00, execution_date=20241114T203841, start_date=20241114T203848, end_date=20241114T203848
[2024-11-14T20:38:48.832+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T20:38:48.833+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task bash_task_tar (Bash command failed. The command returned a non-zero exit code 2.; 248)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-14T20:38:48.861+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-14T20:38:48.873+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-11-14T20:38:48.892+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T20:38:48.896+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
