[2024-11-14T20:54:25.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T20:54:25.314+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_data_into_Postgres.PostgresOperator_task_economy manual__2024-11-14T20:54:13.924706+00:00 [queued]>
[2024-11-14T20:54:25.359+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_data_into_Postgres.PostgresOperator_task_economy manual__2024-11-14T20:54:13.924706+00:00 [queued]>
[2024-11-14T20:54:25.361+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-14T20:54:25.413+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): PostgresOperator_task_economy> on 2024-11-14 20:54:13.924706+00:00
[2024-11-14T20:54:25.444+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T20:54:25.463+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2024-11-14T20:54:25.442+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Extract_data_into_Postgres', 'PostgresOperator_task_economy', 'manual__2024-11-14T20:54:13.924706+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_download.py', '--cfg-path', '/tmp/tmpi8eiffu5']
[2024-11-14T20:54:25.479+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask PostgresOperator_task_economy
[2024-11-14T20:54:25.650+0000] {task_command.py:467} INFO - Running <TaskInstance: Extract_data_into_Postgres.PostgresOperator_task_economy manual__2024-11-14T20:54:13.924706+00:00 [running]> on host 5a0a8dfc4e16
[2024-11-14T20:54:25.778+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ProjectIE' AIRFLOW_CTX_DAG_ID='Extract_data_into_Postgres' AIRFLOW_CTX_TASK_ID='PostgresOperator_task_economy' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T20:54:13.924706+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T20:54:13.924706+00:00'
[2024-11-14T20:54:25.789+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T20:54:25.808+0000] {sql.py:266} INFO - Executing: CREATE TABLE IF NOT EXISTS economic_flight (
    date DATE,
    airline VARCHAR(50),
    ch_code VARCHAR(10),
    num_code INTEGER,
    dep_time TIME,
    "from" VARCHAR(50),
    time_taken VARCHAR(10),
    stop VARCHAR(10),
    arr_time TIME,
    "to" VARCHAR(50),
    price INTEGER,
    class VARCHAR(10)
);
[2024-11-14T20:54:25.830+0000] {base.py:84} INFO - Retrieving connection 'postgres_connect_Project'
[2024-11-14T20:54:25.886+0000] {base.py:84} INFO - Retrieving connection 'postgres_connect_Project'
[2024-11-14T20:54:47.009+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 452, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 574, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "host.docker.local" (125.235.4.59), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-14T20:54:47.042+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_data_into_Postgres, task_id=PostgresOperator_task_economy, run_id=manual__2024-11-14T20:54:13.924706+00:00, execution_date=20241114T205413, start_date=20241114T205425, end_date=20241114T205447
[2024-11-14T20:54:47.057+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T20:54:47.058+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task PostgresOperator_task_economy (connection to server at "host.docker.local" (125.235.4.59), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 452, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 574, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "host.docker.local" (125.235.4.59), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-11-14T20:54:47.077+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-14T20:54:47.086+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-11-14T20:54:47.098+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T20:54:47.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
